services:
  inference:
    container_name: inference-us
    env_file:
      - .env
    build: .
    command: python -u /app/app.py
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/inference/D"]
      interval: 60s
      timeout: 200s
      retries: 14
    volumes:
      - ./inference-data:/app/data
    
  updater:
    container_name: updater-us
    build: .
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8000
    command: >
      sh -c "
      while true; do
        python -u /app/update_app.py;
        sleep 24h;
      done
      "
    depends_on:
      inference:
        condition: service_healthy

  worker:
    container_name: worker-us
    image: alloranetwork/allora-offchain-node:latest
    volumes:
      - ./worker-data:/data
    depends_on:
      inference:
        condition: service_healthy
    env_file:
      - ./worker-data/env_file

volumes:
  inference-data:
  worker-data:
